###
POST http://localhost:5135/api/v1/Catalog/items
Content-Type: application/json

{
  "nome": "Caneca .NET",
  "descricao": "Caneca com o logo .NET",
  "categoria": "Canecas e Copos",
  "quantidade": 50,
  "preco": 29.99,
  "descontoPorcentagem": null
}

###
GET http://127.0.0.1:5135/api/v1/Catalog/items